# 1. Exploring & Understanding Your Data

Import Pandas

Before practicing Pandas, we need to import the pandas module first; and the convention is abbreviated as pd:

In [1]:
import numpy as np
import pandas as pd

We'll use one small dataset throughout the tutorial so you can focus on learning the functions instead of switching between different datasets.

In [117]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Bob"],
    "Age": [25, 30, np.nan, 40, 35, 30],
    "Salary": [50000, 60000, 70000, 80000, 60000, 60000],
    "Department": ["HR", "IT", "IT", "Finance", "HR", "IT"]
})


df

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR
5      Bob  30.0   60000         IT

In [78]:
# first five rows of the dataset
df.head()

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR

In [79]:
# last five rows of the dataset
df.tail()

      Name   Age  Salary Department
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR
5      Bob  30.0   60000         IT

In [80]:
# a concise summary of a DataFrame including column types, non-null counts, and memory usage
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Salary      6 non-null      int64
 3   Department  6 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [81]:
# statistical summary such as count, mean, standard deviation, min, max, and quartiles for numerical columns
df.describe()

             Age        Salary
count   5.000000      6.000000
mean   32.000000  63333.333333
std     5.700877  10327.955590
min    25.000000  50000.000000
25%    30.000000  60000.000000
50%    30.000000  60000.000000
75%    35.000000  67500.000000
max    40.000000  80000.000000

In [82]:
# returns a tuple representing the number of rows and columns in a DataFrame
df.shape

(6, 4)

In [83]:
# returns the number of dimensions of a DataFrame (1 for Series, 2 for DataFrame)
df.ndim

2

In [84]:
# returns the column labels of a DataFrame
df.columns

Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')

In [85]:
# returns the row labels (index) of a DataFrame
df.index

RangeIndex(start=0, stop=6, step=1)

In [86]:
# returns a list of row and column labels of a DataFrame
df.axes

[RangeIndex(start=0, stop=6, step=1),
 Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')]

In [87]:
# data types of each column in the DataFrame as a Series
df.dtypes

Name           object
Age           float64
Salary          int64
Department     object
dtype: object

In [88]:
# returns a NumPy representation of the DataFrame without row and column labels
df.values

array([['Alice', 25.0, 50000, 'HR'],
       ['Bob', 30.0, 60000, 'IT'],
       ['Charlie', nan, 70000, 'IT'],
       ['David', 40.0, 80000, 'Finance'],
       ['Eva', 35.0, 60000, 'HR'],
       ['Bob', 30.0, 60000, 'IT']], dtype=object)

# 2. Selecting, Filtering & Sampling Data

In [89]:
# retrieves rows and columns based on label-based indexing
df.loc[0, "Name"]

'Alice'

In [90]:
# retrieves rows and columns based on integer position-based indexing
df.iloc[3,3]

'Finance'

In [91]:
# replaces values where a condition is True, keeping other values unchanged
df["Salary"].mask(df["Salary"] >= 60000, 0)

0    50000
1        0
2        0
3        0
4        0
5        0
Name: Salary, dtype: int64

In [92]:
# replaces values where a condition is False, keeping matching values unchanged
df["Salary"].where(df["Salary"] >= 60000, 0)

0        0
1    60000
2    70000
3    80000
4    60000
5    60000
Name: Salary, dtype: int64

In [93]:
# filters a DataFrame using a string expression
df.query("Salary > 60000")

      Name   Age  Salary Department
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance

In [94]:
# filters rows based on whether values exist in a given list or collection
df["Department"].isin(["HR", "IT"])

0     True
1     True
2     True
3    False
4     True
5     True
Name: Department, dtype: bool

In [95]:
# returns a random sample of rows or columns from a DataFrame
df.sample()

      Name  Age  Salary Department
2  Charlie  NaN   70000         IT

In [96]:
# creates an independent copy of a DataFrame or Series
df.copy()

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR
5      Bob  30.0   60000         IT

# 3. Cleaning & Preparing Data

In [97]:
# returns a Boolean DataFrame indicating missing (NaN) values

df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False  False   False       False
2  False   True   False       False
3  False  False   False       False
4  False  False   False       False
5  False  False   False       False

In [98]:
# returns a Boolean DataFrame indicating non-missing values

df.notnull()

   Name    Age  Salary  Department
0  True   True    True        True
1  True   True    True        True
2  True  False    True        True
3  True   True    True        True
4  True   True    True        True
5  True   True    True        True

In [99]:
# replaces missing (NaN) values with a specified value or method

df["Age"].fillna(32.5)

0    25.0
1    30.0
2    32.5
3    40.0
4    35.0
5    30.0
Name: Age, dtype: float64

In [100]:
# removes rows or columns that contain missing (NaN) values

df.dropna()

    Name   Age  Salary Department
0  Alice  25.0   50000         HR
1    Bob  30.0   60000         IT
3  David  40.0   80000    Finance
4    Eva  35.0   60000         HR
5    Bob  30.0   60000         IT

In [101]:
# returns a Boolean Series indicating duplicate rows in a DataFrame

df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [102]:
# removes duplicate rows from a DataFrame

df.drop_duplicates()

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR

### Convert to Category

In [103]:
# converts the data type of a Series or DataFrame columns

df["Department"].astype("category")

0         HR
1         IT
2         IT
3    Finance
4         HR
5         IT
Name: Department, dtype: category
Categories (3, object): ['Finance', 'HR', 'IT']

In [104]:
# changes the names of columns or index labels in a DataFrame

df.rename(columns={"Salary": "Income"})

      Name   Age  Income Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR
5      Bob  30.0   60000         IT

In [105]:
# removes specified rows or columns from a DataFrame

df.drop(columns="Salary")

      Name   Age Department
0    Alice  25.0         HR
1      Bob  30.0         IT
2  Charlie   NaN         IT
3    David  40.0    Finance
4      Eva  35.0         HR
5      Bob  30.0         IT

In [106]:
# removes and returns a specified column from a DataFrame

ages = df.pop("Age")

In [107]:
df

      Name  Salary Department
0    Alice   50000         HR
1      Bob   60000         IT
2  Charlie   70000         IT
3    David   80000    Finance
4      Eva   60000         HR
5      Bob   60000         IT

In [108]:
# inserts a new column into a specified position in a DataFrame

df.insert(1, "Country", "USA")

In [109]:
df

      Name Country  Salary Department
0    Alice     USA   50000         HR
1      Bob     USA   60000         IT
2  Charlie     USA   70000         IT
3    David     USA   80000    Finance
4      Eva     USA   60000         HR
5      Bob     USA   60000         IT

### Insert a Column at the Beginning

In [110]:
df.insert(0, "EmployeeID", [101, 102, 103, 104, 105, 106])

In [111]:
df

   EmployeeID     Name Country  Salary Department
0         101    Alice     USA   50000         HR
1         102      Bob     USA   60000         IT
2         103  Charlie     USA   70000         IT
3         104    David     USA   80000    Finance
4         105      Eva     USA   60000         HR
5         106      Bob     USA   60000         IT

# 4. Sorting, Statistics & Aggregation

In [112]:
# sorts a DataFrame or Series by the values in one or more columns, either in ascending or descending order.

df.sort_values

<bound method DataFrame.sort_values of    EmployeeID     Name Country  Salary Department
0         101    Alice     USA   50000         HR
1         102      Bob     USA   60000         IT
2         103  Charlie     USA   70000         IT
3         104    David     USA   80000    Finance
4         105      Eva     USA   60000         HR
5         106      Bob     USA   60000         IT>

In [113]:
df.sort_values(by="Salary")

   EmployeeID     Name Country  Salary Department
0         101    Alice     USA   50000         HR
1         102      Bob     USA   60000         IT
5         106      Bob     USA   60000         IT
4         105      Eva     USA   60000         HR
2         103  Charlie     USA   70000         IT
3         104    David     USA   80000    Finance

In [114]:
df.sort_values(by="Salary", ascending=False)

   EmployeeID     Name Country  Salary Department
3         104    David     USA   80000    Finance
2         103  Charlie     USA   70000         IT
4         105      Eva     USA   60000         HR
1         102      Bob     USA   60000         IT
5         106      Bob     USA   60000         IT
0         101    Alice     USA   50000         HR

In [115]:
df.sort_values(by=["Department", "Salary"])

   EmployeeID     Name Country  Salary Department
3         104    David     USA   80000    Finance
0         101    Alice     USA   50000         HR
4         105      Eva     USA   60000         HR
1         102      Bob     USA   60000         IT
5         106      Bob     USA   60000         IT
2         103  Charlie     USA   70000         IT

Sorts departments alphabetically. \
Sorts salaries within each department.

In [118]:
df.sort_values(
    by="Age",
    na_position="first"
)

      Name   Age  Salary Department
2  Charlie   NaN   70000         IT
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
5      Bob  30.0   60000         IT
4      Eva  35.0   60000         HR
3    David  40.0   80000    Finance

Put Missing Values First

In [119]:
df.sort_values(
    by="Salary",
    inplace=True
)
df

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
5      Bob  30.0   60000         IT
4      Eva  35.0   60000         HR
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance

The original DataFrame is modified directly.

In [120]:
# sorts a DataFrame or Series by its row or column index labels.

df.sort_index()

      Name   Age  Salary Department
0    Alice  25.0   50000         HR
1      Bob  30.0   60000         IT
2  Charlie   NaN   70000         IT
3    David  40.0   80000    Finance
4      Eva  35.0   60000         HR
5      Bob  30.0   60000         IT

In [121]:
df.sort_index(axis=1)

    Age Department     Name  Salary
0  25.0         HR    Alice   50000
1  30.0         IT      Bob   60000
5  30.0         IT      Bob   60000
4  35.0         HR      Eva   60000
2   NaN         IT  Charlie   70000
3  40.0    Finance    David   80000

In [122]:
# returns the unique values from a Series as a NumPy array.

df["Department"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [123]:
# counts the number of distinct (unique) values in a Series or DataFrame

df["Department"].nunique()

3

In [124]:
# counts the frequency of each unique value in a Series and returns the results in descending order.

df["Department"].value_counts()

Department
IT         3
HR         2
Finance    1
Name: count, dtype: int64

In [125]:
# groups rows that share the same value(s) in one or more columns, allowing aggregate calculations on each group.

df.groupby("Department")["Salary"].mean()

Department
Finance    80000.000000
HR         55000.000000
IT         63333.333333
Name: Salary, dtype: float64

In [126]:
# applies one or multiple aggregation functions (such as sum, mean, min, or max) to a DataFrame, Series, or grouped data.

df["Salary"].agg(["min", "max", "mean", "median", "sum"])

min        50000.000000
max        80000.000000
mean       63333.333333
median     60000.000000
sum       380000.000000
Name: Salary, dtype: float64

In [60]:
df.groupby("Department").agg(
    Average_Salary=("Salary", "mean"),
    Highest_Salary=("Salary", "max"),
    Employee_Count=("Name", "count")
)

            Average_Salary  Highest_Salary  Employee_Count
Department
Finance       80000.000000           80000               1
HR            55000.000000           60000               2
IT            63333.333333           70000               3

In [127]:
# creates a spreadsheet-style summary table by grouping and aggregating data across rows and columns.

pd.pivot_table(
    df,
    values="Salary",
    index="Department"
)

                  Salary
Department
Finance     80000.000000
HR          55000.000000
IT          63333.333333

In [62]:
pd.pivot_table(
    df,
    values="Name",
    index="Department",
    aggfunc="count"
)

            Name
Department
Finance        1
HR             2
IT             3

In [128]:
# assigns a ranking to values in a Series or DataFrame based on their relative order.

df["Salary"].rank()

0    1.0
1    3.0
5    3.0
4    3.0
2    5.0
3    6.0
Name: Salary, dtype: float64

In [64]:
df["Salary"].rank(ascending=False)

0    6.0
1    4.0
5    4.0
4    4.0
2    2.0
3    1.0
Name: Salary, dtype: float64

In [65]:
df["Age"].rank()

0    1.0
1    2.5
5    2.5
4    4.0
2    NaN
3    5.0
Name: Age, dtype: float64

In [66]:
df["Salary"].rank(method="min")

0    1.0
1    2.0
5    2.0
4    2.0
2    5.0
3    6.0
Name: Salary, dtype: float64

In [129]:
# returns the top n largest values or rows based on a specified column.

df.nlargest(1, "Salary")

    Name   Age  Salary Department
3  David  40.0   80000    Finance

In [130]:
# returns the top n smallest values or rows based on a specified column.

df.nsmallest(1, "Salary")

    Name   Age  Salary Department
0  Alice  25.0   50000         HR

In [131]:
# applies a custom function to each row, column, or element of a DataFrame or Series.

df["Salary"].apply(lambda x: x * 2)

0    100000
1    120000
5    120000
4    120000
2    140000
3    160000
Name: Salary, dtype: int64

In [70]:
df["Name"].apply(str.upper)

0      ALICE
1        BOB
5        BOB
4        EVA
2    CHARLIE
3      DAVID
Name: Name, dtype: object

# 5. Combining & Reshaping Data

In [132]:
# make the second dataset

department_info = pd.DataFrame({
    "Department": ["HR", "IT", "Finance", "Marketing"],
    "Manager": ["Sarah", "Michael", "James", "Emma"]
})

print(department_info)

  Department  Manager
0         HR    Sarah
1         IT  Michael
2    Finance    James
3  Marketing     Emma

In [133]:
# Inner Join (Default)
merged = pd.merge(df, department_info, on="Department")

print(merged)

      Name   Age  Salary Department  Manager
0    Alice  25.0   50000         HR    Sarah
1      Bob  30.0   60000         IT  Michael
2      Bob  30.0   60000         IT  Michael
3      Eva  35.0   60000         HR    Sarah
4  Charlie   NaN   70000         IT  Michael
5    David  40.0   80000    Finance    James

In [134]:
# Left Join
pd.merge(df, department_info,
         on="Department",
         how="left")

      Name   Age  Salary Department  Manager
0    Alice  25.0   50000         HR    Sarah
1      Bob  30.0   60000         IT  Michael
2      Bob  30.0   60000         IT  Michael
3      Eva  35.0   60000         HR    Sarah
4  Charlie   NaN   70000         IT  Michael
5    David  40.0   80000    Finance    James

In [74]:
# Right Join
pd.merge(df,
         department_info,
         on="Department",
         how="right")

   EmployeeID     Name Country   Age   Salary Department  Manager
0       101.0    Alice     USA  25.0  50000.0         HR    Sarah
1       105.0      Eva     USA  35.0  60000.0         HR    Sarah
2       102.0      Bob     USA  30.0  60000.0         IT  Michael
3       106.0      Bob     USA  30.0  60000.0         IT  Michael
4       103.0  Charlie     USA   NaN  70000.0         IT  Michael
5       104.0    David     USA  40.0  80000.0    Finance    James
6         NaN      NaN     NaN   NaN      NaN  Marketing     Emma

In [75]:
# Outer Join
pd.merge(df,
         department_info,
         on="Department",
         how="outer")

   EmployeeID     Name Country   Age   Salary Department  Manager
0       104.0    David     USA  40.0  80000.0    Finance    James
1       101.0    Alice     USA  25.0  50000.0         HR    Sarah
2       105.0      Eva     USA  35.0  60000.0         HR    Sarah
3       102.0      Bob     USA  30.0  60000.0         IT  Michael
4       106.0      Bob     USA  30.0  60000.0         IT  Michael
5       103.0  Charlie     USA   NaN  70000.0         IT  Michael
6         NaN      NaN     NaN   NaN      NaN  Marketing     Emma

In [138]:
# combines two or more DataFrames or Series by stacking them vertically (rows) or horizontally (columns).

pd.concat([df, department_info])

      Name   Age   Salary Department  Manager
0    Alice  25.0  50000.0         HR      NaN
1      Bob  30.0  60000.0         IT      NaN
5      Bob  30.0  60000.0         IT      NaN
4      Eva  35.0  60000.0         HR      NaN
2  Charlie   NaN  70000.0         IT      NaN
3    David  40.0  80000.0    Finance      NaN
0      NaN   NaN      NaN         HR    Sarah
1      NaN   NaN      NaN         IT  Michael
2      NaN   NaN      NaN    Finance    James
3      NaN   NaN      NaN  Marketing     Emma

In [137]:
# sets one or more existing columns as the index of a DataFrame.

df.set_index("Name")

          Age  Salary Department
Name
Alice    25.0   50000         HR
Bob      30.0   60000         IT
Bob      30.0   60000         IT
Eva      35.0   60000         HR
Charlie   NaN   70000         IT
David    40.0   80000    Finance

In [139]:
# resets the index of a DataFrame to the default integer index and optionally converts the current index into a column.

df.reset_index()

   index     Name   Age  Salary Department
0      0    Alice  25.0   50000         HR
1      1      Bob  30.0   60000         IT
2      5      Bob  30.0   60000         IT
3      4      Eva  35.0   60000         HR
4      2  Charlie   NaN   70000         IT
5      3    David  40.0   80000    Finance

# 6. Mathematical & Element-wise Operations

In [140]:
# performs element-wise addition between DataFrames or Series, automatically aligning data by index and column labels.

df["Salary"].add(1000)

0    51000
1    61000
5    61000
4    61000
2    71000
3    81000
Name: Salary, dtype: int64

In [141]:
df["Age"].add(df["Salary"])

0    50025.0
1    60030.0
5    60030.0
4    60035.0
2        NaN
3    80040.0
dtype: float64

In [142]:
# performs element-wise subtraction between DataFrames or Series, automatically aligning data by index and column labels.

df["Salary"].sub(df["Age"])

0    49975.0
1    59970.0
5    59970.0
4    59965.0
2        NaN
3    79960.0
dtype: float64

In [144]:
# performs element-wise multiplication between DataFrames or Series, automatically aligning data by index and column labels.

df["Age"].mul(df["Salary"], fill_value=1)

0    1250000.0
1    1800000.0
5    1800000.0
4    2100000.0
2      70000.0
3    3200000.0
dtype: float64

In [146]:
# performs element-wise division between DataFrames or Series, automatically aligning data by index and column labels.

df[["Age", "Salary"]].div(10)

   Age  Salary
0  2.5  5000.0
1  3.0  6000.0
5  3.0  6000.0
4  3.5  6000.0
2  NaN  7000.0
3  4.0  8000.0